### PR TITLE
Fix podspec and Swift issue

### PR DESCRIPTION
**Pull request by kyleclegg**
Fixes an issue with the podspec file and updates Swift code for latest compatibility.

### CODE REVIEW

**Comment by kyleclegg** [comment]
@Jobeso would love to see this merged! Would allow me (and other Cocoapods users) to use `react-native-story-share` directly rather than my forked version.

**Comment by ciawalsh** [comment]
Bumping as a reminder! 😄

**Comment by Jobeso** [comment]
@kyleclegg thanks for your work
@ciawalsh thanks for the reminder

Sorry for the waiting time, both of you. Just published `0.4.1` including this fix.

**Comment by franznkemaka** [comment]
Hi @kyleclegg,

what was the exact issue with this? I'm currently using Swift5 and it won't work with these changes, I have to make a regression of your PR before it works. Do you have an idea, why it is happening?

Thanks

**Comment by kyleclegg** [comment]
The issue was `UIImage`'s pngData API changed slightly and would no longer compile using the old syntax.

**Comment by franznkemaka** [comment]
Thanks for the reply @kyleclegg

**Pull request merged**
