### PR TITLE
Use root project build.gradle configurations

### PR DESCRIPTION
**Pull request by franznkemaka**
Use root app compileSdkVersion, buildToolsVersion,  minSdkVersion & targetSdkVersion to avoid error when running
$ gradlew assembleRelease

### CODE REVIEW

**Comment by Jobeso** [comment]
Hey, thanks for your PR. Code looks good, great contribution. I'll test it and then create a new release with it.

**Comment by franznkemaka** [comment]
> Hey, thanks for your PR. Code looks good, great contribution. I'll test it and then create a new release with it.

Thank you! it would be nice, because everytime i run npm install it reuses the old build.gradle configs.
Nice library, simple & functional!

**Comment by Jobeso** [comment]
v0.4.0 is live containing your changes, thanks for the PR

**Comment by franznkemaka** [comment]
> v0.4.0 is live containing your changes, thanks for the PR

Thanks very much!

**Pull request merged**
